### ISSUE TITLE
[FRONTEND] Make app responsive

### ISSUE THREAD

**Issue by extrange** [chaneln9/todhay-app#11]
As it is, the tables don't format nicely on mobile, and the number of columns for Lists and Wishlists don't change with the viewport size, making it hard to view on mobile.

**Comment by chaneln9** [comment]
I think it is kind of responsive [now](https://github.com/chaneln9/todhay-app/commit/84feb062daa3ace3835ff6d7df493c9bf61ac1c2). 
May look again if this were to be used on mobile.
