### ISSUE TITLE
[FRONTEND] Use autocomplete textfield instead of multiselect for tags in `ListModal`

### ISSUE THREAD

**Issue by extrange** [chaneln9/todhay-app#13]
At present, a multi `select` is used to allow the user to select multiple tags for a list. We should allow a textfield with autocomplete with multiple options, for example [Material UI's](https://mui.com/components/autocomplete/#multiple-values) or [Ant Design's](https://ant.design/components/select/#components-select-demo-multiple).

**Comment by chaneln9** [comment]
Added [`react-select`](https://react-select.com/home).
