### ISSUE TITLE
[FRONTEND] Autosave/Prompt if attempting to close `Todo`/`List`/`Tag`/`Wishlist` without saving

### ISSUE THREAD

**Issue by extrange** [chaneln9/todhay-app#15]
This could either be an autosave-type functionality (a `POST` request to create the object initially, followed by multiple `PUT` requests as the user types), or some check which determines whether the form is dirty and prevents closing with a `Discard unsaved changes?` dialog.

**Comment by chaneln9** [comment]
Disabled `Modal` from closing when backdrop is clicked. 
There is only 3 `Buttons` that will cause the `Modal` to be hidden: Close, Save & Delete. 
User should click Save if they want it to be saved.
