### ISSUE TITLE
[FRONTEND] Consider Electron/Neutralino

### ISSUE THREAD

**Issue by extrange** [chaneln9/todhay-app#17]
**Why**

- No need for `docker compose`
- Simpler launch
- Can potentially eliminate REST API since it's all local
- Everything can be written in JS

**Disadvantages**
- Only viewable locally, not over the web

[Neutralino](https://github.com/neutralinojs/neutralinojs) claims to be much lighter than Electron and is picking up in popularity.

**Comment by chaneln9** [comment]
Maybe for something else. I like my API.
