### ISSUE TITLE
[FRONTEND] Color List cards/Tags

### ISSUE THREAD

**Issue by extrange** [chaneln9/todhay-app#6]
At the moment List cards are all the same color. Perhaps have some kind of mapping between tags and the list color? Could be in the backend as a field on the `Tags` model as well, or hardcoded on the frontend.

Alternatively, the cards could be all the same color, but the tags themselves can be color coded and the user can choose the color. This can be stored in the backend as a `color` field (e.g. '8b8b8b').

**Comment by chaneln9** [comment]
Added two colors for `Lists` with and without `due_date`.
Differentiated `Tags` by whether they are a topic (e.g. NLP, Tax) vs not a topic (e.g. Health, Finances). Different colors for the different types.
Not going for too much customization.
